"""ODB++ parser tests against a synthesised minimal archive.

Real ODB++ archives are large (thousands of small files) and usually
derive from proprietary EDA exports, so checking one into the repo is
impractical. Instead, this test synthesises a small but structurally
valid ODB++ directory tree inside a temp dir, tars it, hands it to the
parser, and asserts the parser extracts the expected entities.

The goal isn't parser thoroughness — that's covered by the env-gated
``TestRealODBParsing`` class in ``test_integration_odb.py`` running
against a real design — but to guarantee the parser handles the format
envelope (matrix, stephdr, profile, eda/data, layer features) without
depending on an external file.
"""
from __future__ import annotations

import tarfile
from pathlib import Path

import pytest

from mcp_pcb_emcopilot.parsers.odb_parser import ODBParser


def _write(root: Path, rel: str, content: str) -> None:
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content)


def _synth_odb_tree(base: Path) -> Path:
    """Build a minimal ODB++ directory under ``base`` and return its root."""
    root = base / "odb"
    root.mkdir(parents=True, exist_ok=True)

    # ---------- misc/info ----------
    _write(root, "misc/info", (
        "UNITS=MM\n"
        "JOB_NAME=synthetic_test\n"
    ))

    # ---------- matrix/matrix (layer stackup) ----------
    # Two signal layers plus one dielectric so the parser produces a
    # non-trivial stackup. Layer types follow ODB++ conventions.
    _write(root, "matrix/matrix", (
        "STEP {\n"
        "    COL=1\n"
        "    NAME=pcb\n"
        "    ID=0\n"
        "}\n"
        "LAYER {\n"
        "    COL=1\n"
        "    ROW=1\n"
        "    CONTEXT=BOARD\n"
        "    TYPE=SIGNAL\n"
        "    NAME=top\n"
        "    POLARITY=POSITIVE\n"
        "    START_NAME=top\n"
        "    END_NAME=top\n"
        "}\n"
        "LAYER {\n"
        "    COL=1\n"
        "    ROW=2\n"
        "    CONTEXT=BOARD\n"
        "    TYPE=DIELECTRIC\n"
        "    NAME=core1\n"
        "    POLARITY=POSITIVE\n"
        "    START_NAME=top\n"
        "    END_NAME=bottom\n"
        "}\n"
        "LAYER {\n"
        "    COL=1\n"
        "    ROW=3\n"
        "    CONTEXT=BOARD\n"
        "    TYPE=SIGNAL\n"
        "    NAME=bottom\n"
        "    POLARITY=POSITIVE\n"
        "    START_NAME=bottom\n"
        "    END_NAME=bottom\n"
        "}\n"
    ))

    # ---------- step header ----------
    _write(root, "steps/pcb/stephdr", (
        "UNITS=MM\n"
        "X_DATUM=0\n"
        "Y_DATUM=0\n"
        "ID=1\n"
    ))

    # ---------- step profile (board outline: 50x30 mm rectangle) ----------
    _write(root, "steps/pcb/profile", (
        "#Feature file generated by synthetic-test\n"
        "UNITS=MM\n"
        "OB 0 0 I\n"
        "OS 50 0\n"
        "OS 50 30\n"
        "OS 0 30\n"
        "OS 0 0\n"
        "OE\n"
    ))

    # ---------- netlists/cadnet — net names ----------
    # ODB++ cadnet format: lines starting with ``$`` declare a net; the
    # parser picks up ``$<num> <name>`` and creates ODBNet entries.
    _write(root, "steps/pcb/netlists/cadnet/netlist", (
        "H optimize yes\n"
        "$0 GND\n"
        "$1 VCC_3V3\n"
        "$2 SIG1\n"
    ))

    # ---------- layer features: one trace on top, one pad, one via ----------
    _write(root, "steps/pcb/layers/top/features", (
        "UNITS=MM\n"
        "L 1.0 1.0 10.0 1.0 0 P 0\n"
    ))
    _write(root, "steps/pcb/layers/bottom/features", (
        "UNITS=MM\n"
        "L 1.0 2.0 10.0 2.0 0 P 0\n"
    ))

    return root


@pytest.fixture
def synthetic_odb_archive(tmp_path) -> Path:
    """Synthesise a minimal ODB++ directory and tar it to a .tgz."""
    odb_root = _synth_odb_tree(tmp_path)
    archive = tmp_path / "synthetic.tgz"
    with tarfile.open(archive, "w:gz") as tar:
        tar.add(odb_root, arcname="odb")
    return archive


def test_parser_accepts_synthetic_archive(synthetic_odb_archive):
    """The parser must extract a .tgz and return structured data."""
    parser = ODBParser()
    data = parser.parse(str(synthetic_odb_archive))
    assert data is not None


def test_synthetic_archive_yields_layers(synthetic_odb_archive):
    parser = ODBParser()
    data = parser.parse(str(synthetic_odb_archive))
    # Exactly the three layers declared in matrix/matrix should be parsed.
    names = {l.name for l in data.layers}
    assert names == {"top", "core1", "bottom"}


def test_synthetic_archive_yields_nets(synthetic_odb_archive):
    parser = ODBParser()
    data = parser.parse(str(synthetic_odb_archive))
    names = {n.name for n in data.nets}
    # Synthetic netlist declared GND / VCC_3V3 / SIG1 — parser should pick at least one.
    assert names & {"GND", "VCC_3V3", "SIG1"}


def test_synthetic_archive_has_profile(synthetic_odb_archive):
    parser = ODBParser()
    data = parser.parse(str(synthetic_odb_archive))
    # Board outline should reflect the 50x30mm rectangle we drew.
    # ``ODBData.outline`` is the parsed profile (ODBBoardOutline); its
    # own ``width_mm`` / ``height_mm`` come from the outline bounding box.
    if data.outline is not None and data.outline.outline:
        if data.outline.width_mm:
            assert 40 <= data.outline.width_mm <= 60
        if data.outline.height_mm:
            assert 20 <= data.outline.height_mm <= 40
